# model/tokenizer
model_name: "distilgpt2"
tokenizer_name: "distilgpt2"
gradient_checkpointing: true
save_name: # CHANGE

# data
streaming: false
num_proc: 1
dataset_path: "data"
max_length: 1024
batch_size: 32

# train dynamics
lr: 2.0e-5
min_lr: 0 
weight_decay: 0.0
eval_every: 500
eval_steps: 105
save_every: 500
log_grads_every: 100
output_dir: "result"
checkpoint: null
lora: false
warmup_steps: 50
num_epochs: 1

# logging
wandb: false
wandb_entity: # CHANGE
wandb_project_name: # CHANGE
seed: 42

